### PR TITLE
scr-1050

### PR DESCRIPTION
**Pull request by thet**
**NOTE**: This introduces ``ftw.upgrade``. In order to use it you need to install it via the addon controlpanel or portal_settings.

Related PRs:
- https://github.com/syslabcom/recensio.buildout/pull/1
- https://github.com/syslabcom/recensio.policy/pull/1
- https://github.com/syslabcom/recensio.theme/pull/3
- https://github.com/syslabcom/recensio.translations/pull/1

### CODE REVIEW

**Comment by reinhardt** [comment]
In quaive we have [an upgrade step that installs ftw.upgrade](https://github.com/quaive/ploneintranet/blob/master/src/ploneintranet/upgrade/v21/10000000000001_install_ftw_upgrade/upgrade.py). Couldn't we add that here as well?

**Comment by thet** [comment]
Very good, I'll add it.
However, it uses ftw.upgrade to install ftw.upgrade? Interesting...

**Comment by reinhardt** [comment]
You can use the regular portal_setup to install ftw.upgrade steps as well.

**Comment by reinhardt** [comment]
When trying to run the upgrade step that installs ftw.upgrade I get

```
KeyError: 'Unknown context "ftw.upgrade:default"'
```

Manually installing ftw.upgrade works.

I noticed that in quaive we don't have

```
<include package="ftw.upgrade" />
```

and the documentation doesn't mention this either. However, removing it doesn't seem to change anything (same error).

I wouldn't spend too much time investigating because we can simply use the manual installation, but if you happen to have an idea do let me know.

**Comment by reinhardt** [comment]
I'll extend the upgrade step that sets up the main navigation to also remove the secondary nav portlet from the “Rezensionen” folder. The respective HTML has been removed from the template and I get a (non-fatal) error because it's not found any more.

**Review by reinhardt — APPROVED** [review]

**Pull request merged**
